# VPN Services Pod
# Containers: gluetun (VPN), qbittorrent, sabnzbd, prowlarr
# All containers share gluetun's network namespace for VPN routing
#
# SECURITY: WireGuard key is in a SEPARATE file (wireguard-secret.yaml)
# that is created during setup and never committed to git.
#
# Template file - edit quadlet/ source files for changes
apiVersion: v1
kind: Pod
metadata:
  name: vpn-services
  labels:
    app: vpn-services
spec:
  containers:
    # =========================================================================
    # Gluetun - VPN Gateway
    # =========================================================================
    - name: gluetun
      image: docker.io/qmcgaw/gluetun:v3
      securityContext:
        privileged: true
        capabilities:
          add:
            - NET_ADMIN
      env:
        - name: VPN_SERVICE_PROVIDER
          value: "nordvpn"
        - name: VPN_TYPE
          value: "wireguard"
        - name: WIREGUARD_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: wireguard-key
              key: key
        - name: SERVER_COUNTRIES
          value: "{{SERVER_COUNTRIES}}"
        - name: TZ
          value: "{{TZ}}"
        # DNS Privacy Settings
        - name: DNS_KEEP_NAMESERVER
          value: "on"
        - name: DOT
          value: "on"
        - name: DOT_PROVIDERS
          value: "cloudflare"
        - name: DOT_IPV6
          value: "off"
        # Firewall Settings
        - name: FIREWALL_VPN_INPUT_PORTS
          value: ""
        - name: FIREWALL_INPUT_PORTS
          value: "8090,8080,9696"
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
      volumeMounts:
        - name: gluetun-config
          mountPath: /gluetun

    # =========================================================================
    # qBittorrent - Torrent Client (uses gluetun's network)
    # =========================================================================
    - name: qbittorrent
      image: lscr.io/linuxserver/qbittorrent:5.1.4
      env:
        - name: PUID
          value: "{{PUID}}"
        - name: PGID
          value: "{{PGID}}"
        - name: TZ
          value: "{{TZ}}"
        - name: WEBUI_PORT
          value: "8090"
      volumeMounts:
        - name: qbittorrent-config
          mountPath: /config
        - name: torrents
          mountPath: /data/torrents

    # =========================================================================
    # SABnzbd - Usenet Downloader (uses gluetun's network)
    # =========================================================================
    - name: sabnzbd
      image: lscr.io/linuxserver/sabnzbd:4.5.5
      env:
        - name: PUID
          value: "{{PUID}}"
        - name: PGID
          value: "{{PGID}}"
        - name: TZ
          value: "{{TZ}}"
      volumeMounts:
        - name: sabnzbd-config
          mountPath: /config
        - name: usenet
          mountPath: /data/usenet

    # =========================================================================
    # Prowlarr - Indexer Manager (uses gluetun's network)
    # =========================================================================
    - name: prowlarr
      image: lscr.io/linuxserver/prowlarr:2.3.0
      env:
        - name: PUID
          value: "{{PUID}}"
        - name: PGID
          value: "{{PGID}}"
        - name: TZ
          value: "{{TZ}}"
      volumeMounts:
        - name: prowlarr-config
          mountPath: /config
        # Custom indexer definitions (1337x-onion, etc.)
        - name: prowlarr-definitions
          mountPath: /config/Definitions/Custom
          readOnly: true

  volumes:
    - name: gluetun-config
      persistentVolumeClaim:
        claimName: gluetun-config
    - name: qbittorrent-config
      persistentVolumeClaim:
        claimName: qbittorrent-config
    - name: sabnzbd-config
      persistentVolumeClaim:
        claimName: sabnzbd-config
    - name: prowlarr-config
      persistentVolumeClaim:
        claimName: prowlarr-config
    - name: torrents
      hostPath:
        path: {{DATA_PATH}}/torrents
        type: Directory
    - name: usenet
      hostPath:
        path: {{DATA_PATH}}/usenet
        type: Directory
    # Custom indexer definitions - copied alongside quadlet files
    - name: prowlarr-definitions
      hostPath:
        path: {{PROWLARR_DEFINITIONS_PATH}}
        type: Directory
